import { describe, it, expect } from "vitest";
import { renderClaudeMd } from "../../../src/generators/claude";
import { renderAgentsMd } from "../../../src/generators/agents";
import { renderGeminiMd } from "../../../src/generators/gemini";
import { renderCursorRules, renderCursorMdc } from "../../../src/generators/cursor";
import type { BeaconConfig } from "../../../src/core/config";

const cfg: BeaconConfig = {
  version: "1.0",
  projectType: "web-app",
  categories: ["reference", "architecture", "adr", "plans", "backlog", "evaluations", "business", "integrations", "operations"],
  agents: ["claude", "cursor", "codex", "gemini"],
  language: "en",
};

describe("vendor generators", () => {
  it("CLAUDE.md has BEACON header and links to convention.md", () => {
    const md = renderClaudeMd(cfg);
    expect(md).toContain("<!-- generated by beacon");
    expect(md).toContain("docs/_meta/convention.md");
  });

  it("CLAUDE.md includes universal + project-specific + decision table", () => {
    const md = renderClaudeMd(cfg);
    expect(md).toMatch(/Universal rules/i);
    expect(md).toMatch(/Project-specific rules/i);
    expect(md).toMatch(/Where does X go/i);
  });

  it("AGENTS.md has same shape as CLAUDE.md but addresses Codex/Copilot", () => {
    const md = renderAgentsMd(cfg);
    expect(md).toContain("<!-- generated by beacon");
    expect(md).toMatch(/agents.md/i);
  });

  it("GEMINI.md generated", () => {
    expect(renderGeminiMd(cfg)).toContain("<!-- generated by beacon");
  });

  it(".cursorrules is terse (no decision table) and includes universal rules", () => {
    const out = renderCursorRules(cfg);
    expect(out).toContain("<!-- generated by beacon");
    expect(out).toMatch(/Universal rules/i);
    expect(out).not.toMatch(/Where does X go/i);
  });

  it(".cursor/rules/beacon.mdc has frontmatter with description and globs", () => {
    const out = renderCursorMdc(cfg);
    expect(out.startsWith("---")).toBe(true);
    expect(out).toContain("description:");
    expect(out).toContain("globs:");
    expect(out).toMatch(/Universal rules/i);
  });
});
