import { COMMAND_SCHEMA, TOP_LEVEL_COMMANDS } from "./schema";

/**
 * Generate a bash completion script for `beacon`.
 *
 * Install with:
 *   beacon completion bash > ~/.local/share/bash-completion/completions/beacon
 *
 * The script handles:
 *  - Top-level commands
 *  - Per-command flags (positional flags only — flag values come from a separate case)
 *  - Static positional values (e.g., addon names, doc types)
 *  - Dynamic second positional via filesystem glob (e.g., archive plan <slug>)
 *  - Flag values (e.g., --type web-app, --explain stale-plans)
 */
export function renderBashCompletion(): string {
  const topLevel = TOP_LEVEL_COMMANDS.join(" ");

  const perCommandCases: string[] = [];

  for (const cmd of COMMAND_SCHEMA) {
    const parts: string[] = [];

    // Flag-value completion (when prev word is a flag that takes a value)
    if (cmd.flagValues) {
      const flagCases: string[] = [];
      for (const [flag, values] of Object.entries(cmd.flagValues)) {
        flagCases.push(
          `        --${flag})\n          COMPREPLY=( $(compgen -W "${values.join(" ")}" -- "$cur") )\n          return 0\n          ;;`,
        );
      }
      parts.push(`      case "$prev" in\n${flagCases.join("\n")}\n      esac`);
    }

    // First-positional values (e.g., `beacon new <type>`)
    if (cmd.positionalValues && cmd.positionalValues.length > 0) {
      parts.push(
        `      if [[ $COMP_CWORD -eq 2 ]]; then\n        COMPREPLY=( $(compgen -W "${cmd.positionalValues.join(" ")}" -- "$cur") )\n        return 0\n      fi`,
      );
    }

    // Dynamic second-positional (e.g., archive plan <slug>)
    if (cmd.dynamicSecondPositional) {
      const subParts: string[] = [];
      for (const [firstVal, source] of Object.entries(cmd.dynamicSecondPositional)) {
        subParts.push(
          `      if [[ $COMP_CWORD -eq 3 && "\${COMP_WORDS[2]}" == "${firstVal}" ]]; then\n        local items\n        items=$(ls ${source.glob} 2>/dev/null | sed 's|.*/||;s|${source.suffix.replace(/\./g, "\\.")}$||')\n        COMPREPLY=( $(compgen -W "$items" -- "$cur") )\n        return 0\n      fi`,
        );
      }
      parts.push(subParts.join("\n"));
    }

    // Flag completion fallback (when cur starts with `-`)
    if (cmd.flags.length > 0) {
      parts.push(
        `      if [[ "$cur" == -* ]]; then\n        COMPREPLY=( $(compgen -W "${cmd.flags.join(" ")}" -- "$cur") )\n        return 0\n      fi`,
      );
    }

    perCommandCases.push(
      `    ${cmd.name})\n${parts.join("\n")}\n      ;;`,
    );
  }

  return `# bash completion for beacon
# generated by beacon — do not edit by hand
# install: beacon completion bash > ~/.local/share/bash-completion/completions/beacon
# or:      beacon completion bash | sudo tee /etc/bash_completion.d/beacon

_beacon_completion() {
  local cur prev cmd
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd="\${COMP_WORDS[1]:-}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${topLevel}" -- "$cur") )
    return 0
  fi

  case "$cmd" in
${perCommandCases.join("\n")}
  esac
  return 0
}

complete -F _beacon_completion beacon
`;
}
