import { COMMAND_SCHEMA } from "./schema";

/**
 * Generate a fish completion script for `beacon`.
 *
 * Install with:
 *   beacon completion fish > ~/.config/fish/completions/beacon.fish
 *
 * Fish reloads completions automatically — no shell restart needed.
 */
export function renderFishCompletion(): string {
  const lines: string[] = [];
  lines.push("# fish completion for beacon");
  lines.push("# generated by beacon — do not edit by hand");
  lines.push("# install: beacon completion fish > ~/.config/fish/completions/beacon.fish");
  lines.push("");

  // Helper: condition for "current subcommand is X"
  const usingCmd = (name: string) =>
    `__fish_seen_subcommand_from ${name}`;

  // Top-level commands
  for (const cmd of COMMAND_SCHEMA) {
    const desc = cmd.description.replace(/'/g, "\\'");
    lines.push(
      `complete -c beacon -n "__fish_use_subcommand" -a "${cmd.name}" -d '${desc}'`,
    );
  }
  lines.push("");

  for (const cmd of COMMAND_SCHEMA) {
    // First-positional values
    if (cmd.positionalValues && cmd.positionalValues.length > 0) {
      lines.push(`# ${cmd.name} positional values`);
      for (const v of cmd.positionalValues) {
        lines.push(
          `complete -c beacon -n "${usingCmd(cmd.name)}; and not __fish_seen_subcommand_from ${cmd.positionalValues.join(" ")}" -a "${v}"`,
        );
      }
      lines.push("");
    }

    // Dynamic second-positional
    if (cmd.dynamicSecondPositional) {
      lines.push(`# ${cmd.name} dynamic slugs`);
      for (const [firstVal, source] of Object.entries(cmd.dynamicSecondPositional)) {
        lines.push(
          `complete -c beacon -n "${usingCmd(cmd.name)}; and __fish_seen_subcommand_from ${firstVal}" -a "(ls ${source.glob} 2>/dev/null | sed 's|.*/||;s|${source.suffix.replace(/\./g, "\\.")}\\$||')"`,
        );
      }
      lines.push("");
    }

    // Flags
    if (cmd.flags.length > 0) {
      lines.push(`# ${cmd.name} flags`);
      for (const flag of cmd.flags) {
        const long = flag.replace(/^--/, "");
        // Flag value completion
        const values = cmd.flagValues?.[long];
        if (values && values.length > 0) {
          lines.push(
            `complete -c beacon -n "${usingCmd(cmd.name)}" -l ${long} -x -a "${values.join(" ")}"`,
          );
        } else {
          lines.push(`complete -c beacon -n "${usingCmd(cmd.name)}" -l ${long}`);
        }
      }
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}
