import { COMMAND_SCHEMA, TOP_LEVEL_COMMANDS } from "./schema";

/**
 * Generate a zsh completion script for `beacon`.
 *
 * Install with:
 *   beacon completion zsh > "${fpath[1]}/_beacon"
 * Then restart your shell (or `autoload -U compinit && compinit`).
 */
export function renderZshCompletion(): string {
  const topLevelEntries = COMMAND_SCHEMA.map(
    (c) => `'${c.name}:${c.description.replace(/'/g, "'\\''")}'`,
  );
  // Each line except the last needs a trailing backslash to continue the `_values` call.
  const topLevelLines = topLevelEntries
    .map((entry, idx) => `    ${entry}${idx < topLevelEntries.length - 1 ? " \\" : ""}`)
    .join("\n");

  const perCommandCases: string[] = [];

  for (const cmd of COMMAND_SCHEMA) {
    const parts: string[] = [];

    // Flag-value branches
    if (cmd.flagValues) {
      for (const [flag, values] of Object.entries(cmd.flagValues)) {
        parts.push(
          `        if [[ "\${words[CURRENT-1]}" == "--${flag}" ]]; then\n          _values "${flag}" ${values.map((v) => `'${v}'`).join(" ")}\n          return 0\n        fi`,
        );
      }
    }

    // First-positional values
    if (cmd.positionalValues && cmd.positionalValues.length > 0) {
      parts.push(
        `        if (( CURRENT == 3 )); then\n          _values "${cmd.name}" ${cmd.positionalValues.map((v) => `'${v}'`).join(" ")}\n          return 0\n        fi`,
      );
    }

    // Dynamic second-positional
    if (cmd.dynamicSecondPositional) {
      for (const [firstVal, source] of Object.entries(cmd.dynamicSecondPositional)) {
        parts.push(
          `        if (( CURRENT == 4 )) && [[ "\${words[3]}" == "${firstVal}" ]]; then\n          local -a items\n          items=( \${\${(f)"$(ls ${source.glob} 2>/dev/null | sed 's|.*/||;s|${source.suffix.replace(/\./g, "\\.")}$||')"}} )\n          _values "${firstVal}" $items\n          return 0\n        fi`,
        );
      }
    }

    // Flag fallback
    if (cmd.flags.length > 0) {
      parts.push(
        `        _values "flags" ${cmd.flags.map((f) => `'${f}'`).join(" ")}`,
      );
    }

    perCommandCases.push(`      ${cmd.name})\n${parts.join("\n")}\n        ;;`);
  }

  return `#compdef beacon
# zsh completion for beacon
# generated by beacon — do not edit by hand
# install: beacon completion zsh > "\${fpath[1]}/_beacon"

_beacon() {
  local context state line
  typeset -A opt_args

  if (( CURRENT == 2 )); then
    _values "beacon command" \\
${topLevelLines}
    return 0
  fi

  local cmd="\${words[2]}"
  case "$cmd" in
${perCommandCases.join("\n")}
  esac
  return 0
}

_beacon "$@"
`;
}
